---
name: Build kubeadm binary image

on:
  push:
    tag:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare for build binary image
        shell: bash
        run: |
          git describe --tags --always | sed 's/^/IMAGE_TAG=/' >> $GITHUB_ENV
          sed 's/^/KUBE_BUILD_IMAGE_CROSS_TAG=/' build/build-image/cross/VERSION >> $GITHUB_ENV

      - name: Build kubeadm binary
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/kubeadm-bin-image/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBE_BUILD_IMAGE_CROSS_TAG=${KUBE_BUILD_IMAGE_CROSS_TAG}
          outputs: type=local,dest=./

      - name: Prepare for upload
        shell: bash
        run: |
          mv linux_amd64/kubeadm kubeadm-linux-amd64
          mv linux_arm64/kubeadm kubeadm-linux-arm64
          sha256sum kubeadm-linux-{amd64,arm64} > sha256sum.txt

      - name: Release and upload packages
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            sha256sum.txt
            kubeadm-linux-amd64
            kubeadm-linux-arm64
